# Generated by Django 5.2.12 on 2026-03-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cor',
            name='nome',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
